project:
  type: website

ipynb-filters: 
  - quarto_filter.py

exeucte:
  eval: false

website:
  title: "Hamel's Blog"
  image: quarto.png
  page-footer:
    center:
      - icon: linkedin
        href: https://www.linkedin.com/in/hamelhusain/
      - icon: twitter
        href: https://twitter.com/HamelHusain
      - icon: github
        href: https://github.com/hamelsmu
      - icon: rss
        href: index.xml
  favicon: favicon.ico
  open-graph: true
  twitter-card:
     creator: "@HamelHusain"
     card-style: summary
  site-url: "https://hamel.dev/"
  description: "A collection of blogs and talks on machine learning and data science."
  repo-url: https://github.com/hamelsmu/hamel-site
  repo-actions: [edit]
  repo-branch: master
  navbar:
    title: false
    background: dark
    pinned: false
    collapse: false
    left:
    # 🏠 📮 👨🏽‍💻 🍎 🎤 📚
    - text: "Blog"
      href: index.qmd
    # - text: 📮 Blog
    #   href: index.qmd#blog-posts
    # - text: 👨🏽‍💻 About
    #   file: about.qmd
    - text: Projects
      file: oss/opensource.qmd
    # - text: 🍎 Teaching
    #   file: about.qmd
    - text: Talks 
      file: talks.qmd
    - text: Notes
      file: notes/index.qmd
    right:
      - icon: rss
        href: index.xml

  sidebar:
    - title: Notes
      pinned: true
      collapse-level: 1
      style: docked
      contents: notes/**
        # - text: Home
        #   icon: house
        #   href: notes/index.qmd
        # - section: GitHub Actions
        #   contents: notes/actions/*
        # - notes/docker/index.qmd
        # - section: fastai
        #   contents: notes/fastai/*
        # - notes/how-to-learn/index.qmd
        # - section: Jupyter
        #   contents: notes/jupyter/*
        # - section: K8s
        #   href: notes/k8s/index.qmd
        #   contents:
        #     - notes/k8s/02-Basics.qmd
        #     - notes/k8s/03-Secrets.qmd
        #     - section: Storage
        #       contents: notes/k8s/storage/*
        #     - section: Scaling
        #       contents: notes/k8s/scaling/*
        #     - section: Multi-Container pods
        #       contents: notes/k8s/multi_container_pods/*
        #     - notes/k8s/12-StatefulSet.qmd
        #     - notes/k8s/13-JobsCron.qmd
        #     - notes/k8s/14-RolloutsRollbacks.qmd
        #     - section: Helm
        #       contents: notes/k8s/helm/*
        #     - notes/k8s/18-Developer.qmd
        #     - notes/k8s/19-Pod-Lifecycle.qmd
        #     - notes/k8s/20-health-checks.qmd
        #     - notes/k8s/99-Random.qmd
        # - section: Linux
        #   contents: notes/linux/*
        # - text: Pandoc filters
        #   href: notes/pandoc/index.qmd
        # - text: Quarto
        #   href: notes/quarto/index.qmd
        #   contents: notes/quarto/*
        # - text: Programming Languages  
        #   href: notes/programming-languages/index.qmd
        # - text: Web Scraping
        #   href: notes/web-scraping/index.qmd
        #   contents: notes/web-scraping/*
        # - auto: "notes/*"

format:
  html:
    reference-location: document
    theme: [solar, custom.scss]
    css:
      - styles.css
    toc: true
    syntax-definitions: 
    - fomo.xml


