# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hamel',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/hamel',
                'lib_path': 'hamel'},
  'syms': { 'hamel.oai': { 'hamel.oai._to_dt': ('core.html#_to_dt', 'hamel/oai.py'),
                           'hamel.oai.list_models': ('core.html#list_models', 'hamel/oai.py')}}}
